SDKROOT?=..
include $(SDKROOT)/makedefs/nm_common.mk

DEFINES += -D"REGION_AS923"
DEFINES += -D"REGION_AU915"
DEFINES += -D"REGION_US915"
DEFINES += -D"REGION_KR920"
DEFINES += -D"REGION_US868"
DEFINES += -D"REGION_IN865"
DEFINES += -DLORAMAC_CLASSA_ENABLED
